<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/120108/co12010QQ951-0.jpg ",93,241);
$z[1][4]['ddimg']="/uploads/allimg/120108/co12010QQ951-0.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="700";
$z[1][4]['height']="1015";
$z[2]=Array("img"," /uploads/allimg/120108/co12010QQ951-1.jpg ",243,391);
$z[2][4]['ddimg']="/uploads/allimg/120108/co12010QQ951-1.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="902";

?>