
                    <div class="book_next_text">
                    	<dl>
                        <dd class="name_book">[[field:cataloglink/]] [field:booklink/]</dd>
                        <dd class="news_book">[field:contentlink/]2</dd>
                        <dd class="time_book">[field:lastpost function="GetDateMk(@me)"/]</dd>
                        </dl>
                        <div class="clear"></div>
                  	</div>
                    