<?php
$z[0]=Array("bookurl","",106,122);
$z[1]=Array("litpic","@me = (empty(@me['litpic']) ? \"<img src='/images/defaultpic.gif' width='80' height='100' />\" : \"<img src='@me' width='80' height='100' />\"); ",124,307);
$z[1][4]['runphp']="yes";
$z[2]=Array("cataloglink","",387,407);
$z[3]=Array("bookurl","",418,434);
$z[4]=Array("bookname","",436,453);
$z[5]=Array("author","",476,491);
$z[6]=Array("ischeck","",519,535);
$z[7]=Array("description"," if(strlen(@me)>=240) @me = substr(@me,0,240).\"...\";",578,682);
$z[7][4]['runphp']="yes";

?>