<?php
$z[0]=Array("global","",250,276);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",320,350);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",387,414);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",498,542);
$z[3][4]['filename']="aabbccdd_head.htm";
$z[4]=Array("arclist"," \r\n<DL><SPAN class=flr>[field:pubdate function=\"MyDate('m-d',@me)\"/]</SPAN><A href=\"[field:arcurl/]\" target=_blank>[field:title/]</A></DL>\r\n",659,850);
$z[4][4]['row']="24";
$z[4][4]['titlelen']="20";
$z[5]=Array("arclist"," \r\n<DIV class=innr8>\r\n<UL>\r\n  <LI><A href=\"[field:arcurl/]\"><IMG \r\n  src=\"[field:litpic/]\"></A></LI></UL>\r\n<DL>\r\n  <DT class=red_lj><STRONG><A href=\"[field:arcurl/]\" >[field:title/]</A></STRONG></DT>\r\n  <DT>状态：[field:comic/]</DT>\r\n  <DT>作者：[field:author/]</DT>\r\n  <DT>人气：[field:click /]</DT></DL></DIV>\r\n<DIV class=ff></DIV>\r\n",929,1322);
$z[5][4]['row']="10";
$z[5][4]['att']="c";
$z[6]=Array("field","",2384,2413);
$z[6][4]['name']="position";
$z[7]=Array("list"," \r\n<li class=\"red_lj\">\r\n<a href=\"[field:arcurl/]\"><img  src=\"[field:litpic/]\"></a><br><a href=\"[field:arcurl/]\">[field:title/]</a>(<span style=\"color: red;\">[field:comic/]</span>)<br>作者：[field:author/]<br>更新时间：[field:pubdate function=\"MyDate('m-d',@me)\"/]</li>\r\n",2450,2765);
$z[7][4]['pagesize']="10";
$z[8]=Array("pagelist","",2852,2930);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",3035,3079);
$z[9][4]['filename']="aabbccdd_foot.htm";

?>