<?php
$z[0]=Array("bookurl","",105,121);
$z[1]=Array("litpic","@me = ((@me==\"\") ? \"<img src='/images/defaultpic.gif' width='80' height='100'/>\" : \"<img src='@me' width='80' height='100'>\"); ",123,292);
$z[1][4]['runphp']="yes";
$z[2]=Array("bookurl","",371,387);
$z[3]=Array("title","",389,403);
$z[4]=Array("author","",452,467);
$z[5]=Array("author","",469,484);
$z[6]=Array("description","",527,576);
$z[6][4]['function']="cn_substr(@me,60)";

?>