<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",18,95);
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",122,138);
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",157,242);
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",273,288);
$z[4]=Array("imgwidth","",302,320);
$z[5]=Array("alttext","",326,343);
$z[6]=Array("linkurl","",555,571);
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",573,659);
$z[7][4]['runphp']="yes";
$z[8]=Array("alttext","",679,696);
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",736,816);
$z[9][4]['runphp']="yes";

?>