{dede:field name='keywords'}在Dreamweaver中为插入的Flash添{/dede:field}
{dede:field name='description'}Dreamweaver升级到8.0.2后，插入Flash时的代码会有所改变，这是Macromedia为解决IE中的Flash会出现控件激活框而作的更新。要为Flash添加透明等参数有两种方法。{/dede:field}
{dede:field name='title'}在Dreamweaver中为插入的Flash添加透明{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>Dreamweaver升级到8.0.2后，插入Flash时的代码会有所改变，这是Macromedia为解决IE中的Flash会出现控件激活框而作的更新。要为Flash添加透明等参数有两种方法。 </p><p>用Dreamweaver的属性面板为插入的Flash添加透明属性，此方法简单实用。 </p><p>使插入的Flash处于选择状态，点击属性面板中的“参数”，在随即弹出的参数表中添加一行，参数名为“wmode”，值为“transparent”。使用此方法时注意，若页面中有人工输入的Flash ID，此ID将被删除，请在添加完参数后重新输入ID。 </p><p><img src="http://file.chinahtml.com/webdesign/1/2007-05-18/23495383c29c86eda4abe95a02a7bcc1.jpg" border="0" />&nbsp;</p><p>在html代码中为插入的Flash添加透明属性。 </p><p>同样是添加值为“transparent”的“wmode”参数。 </p>
            <p align="center"> </p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
