<?php
$z[0]=Array("spaceurl","",92,110);
$z[1]=Array("face","",139,152);
$z[2]=Array("spaceurl","",193,211);
$z[3]=Array("uname","",230,244);
$z[4]=Array("spaceurl","",281,299);
$z[5]=Array("spaceurl","",352,370);
$z[6]=Array("spaceurl","",434,452);
$z[7]=Array("rankname","",569,587);
$z[8]=Array("jointime","",649,701);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",763,816);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>