
<DIV class=innr8>
<UL>
  <LI><A href="[field:bookurl /]"><IMG   src="[field:litpic/]"></A></LI></UL>
<DL>
  <DT class=red_lj><STRONG><A href="[field:bookurl /]" >[field:bookname/]</A></STRONG></DT>
  <DT>状态：[field:array runphp='yes']@me = (@me['status']==0 ? "连载中" : "已完结"); [/field:array] </DT>
  <DT>作者：[field:author/]</DT>
  <DT>人气：[field:click /]</DT>
  </DL>
  </DIV>
<DIV class=ff></DIV>
