
      <div class="book_article_texttable">
                    	<div class="book_article_texttitle">第{in:field name='chapnum'}{/in:field}章 {in:field name='chaptername'}{/in:field}
                        </div>
                        <div class="book_article_listtext">
                        	<dl id="chapterlist">
                            {in:content}<dd><a href="[field:url/]">第[field:ch/]节 [field:title/]</a></dd>{/in:content}
                            </dl>
                            <div class="clear">
                            </div>
                        </div>
                </div>
                    