<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:comic itemname="漫画状态" autofield="0" notsend="0" type="select" isnull="true" islist="0" default="连载中,已完结"  maxlength="250" page="">
</field:comic>


<field:author itemname="漫画作者" autofield="0" notsend="0" type="textchar" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:author>

