
                        <div class="book_class_form">
                            <dl>
                            <dt><a href="{in:field name='url'}{/in:field}">{in:field name='classname'}{/in:field}：</a></dt>
                            {in:sonlist}<dd> <a href='[field:url/]'>[field:classname/]</a></dd>{/in:sonlist}
                            </dl>
                            <div class="clear">
                            </div>
                        </div>
                        