<?php
$z[0]=Array("sql","：[field:c /] 部",157,244);
$z[0][4]['sql']="select count(ID) as c from dede_archives";
$z[1]=Array("channel","\r\n<a href='[field:typelink /]' style=\"font-size:14px\">[field:typename/]</a> | \r\n",824,953);
$z[1][4]['row']="13";
$z[1][4]['type']="top";
$z[2]=Array("sql","\r\n<A \r\nhref=\"/book/list.php?id=[field:id/]\"><SPAN>[field:classname/]</SPAN></A> </SPAN>\r\n",1026,1215);
$z[2][4]['sql']="Select * From #@__story_catalog WHERE pid='2' order by id ASC limit 0,30";

?>