
<div class="book_news_style_form">
                        	<div class="book_news_style_img"><a href="[field:bookurl/]">[field:litpic runphp='yes']@me = ((@me=="") ? "<img src='/images/defaultpic.gif' width='80' height='100'/>" : "<img src='@me' width='80' height='100'>"); [/field:litpic]</a></div>
                    <div class="book_news_style_text"><h1><a href='[field:bookurl/]'>[field:title/]</a></h1><h2>作者：<a href='search.php?author=[field:author/]'>[field:author/]</a></h2>
                            <h3>[field:description function="cn_substr(@me,60)"/]…</h3>
                            </div>
                        </div>
                        