<DIV class=innr8>
<UL>
  <LI><A href="[field:arcurl/]"><IMG 
  src="[field:litpic/]"></A></LI></UL>
<DL>
  <DT class=red_lj><STRONG><A href="[field:arcurl/]" >[field:title/]</A></STRONG></DT>
  <DT>状态：[field:comic/]</DT>
  <DT>作者：<field:author itemname="漫画作者" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:author></DT>
  <DT>人气：[field:click /]</DT></DL></DIV>
<DIV class=ff></DIV>